spring.datasource.url=jdbc:mysql://remotemysql.com:3306/qGRpS4jwEo
spring.datasource.username=qGRpS4jwEo
spring.datasource.password=EUfSONicTk
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create